### ISSUE TITLE
Using library with VS Code and PlatformIO

### ISSUE THREAD

**Issue by JMyrng** [SPEC-Sensors/DGS#6]
Hi,

I´m trying to import this library into an empty PlatformIO project with the following `platformio.ini` file: 
```
[env:mkrwan1310]
platform = atmelsam
board = mkrwan1310
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/SPEC-Sensors/DGS
```
Microcontroller: Arduino MKR Wan 1310

The PlatformIO library manager reports the following message after building this project: `Could not parse manifest -> Particle is not supported yet`

Does anyone now a solution to this problem?

Best regards

**Comment by dpeaslee** [comment]
I'm not sure I can help here. The sub directory was tested on the particle IDE in 2019. I have not tried any of this on the new particle VS IDE. 
You could try making your own branch and changing the library properties file to add one of these:

1) "architectures A comma-separated list of supported hardware boards that are compatible with your library. If missing or set to *, the library will be available for all architectures. Available values for Particle libraries: spark-core, particle-photon, particle-electron, particle-p1, digistump-oak, bluz, redbear-duo"

2) Also, Im not sure of the effect of including this in the properties file, may have different effect for different IDE's:
dependencies.DGS=2.0.0

If adding to 1) above doesn't help, try removing 2)

Finally, if fixing the properties file allows for starting the project, make sure the Serial, Serial1, etc works for the particle.io board you are using.

**Comment by dpeaslee** [comment]
Here is the sub directory I was referring to:
DGS/examples/DSDK_Photon/

**Comment by JMyrng** [comment]
Thank´s for your hint. I´ve got it working by deleting the Photon boards in the `library.properties` file and deleting the Photon example. Not sure if the second step was really necessary.
